import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'tasks': 'Tasks',
      'appTitle': 'To-do List App',
      'taskListTitle': 'Tasks',
      'addTask': 'Add Task',
      'editTask': 'Edit Task',
      'deleteTask': 'Delete',
      'taskTitleHint': 'Task Title',
      'taskDescriptionHint': 'Description',
      'cancel': 'Cancel',
      'save': 'Save',
      'noTasks': 'No tasks available. Add a new one!',
      'analyticsTitle': 'Productivity Analytics',
      'teamTitle': 'Team Collaboration',
      'priorityLow': 'Low',
      'priorityMedium': 'Medium',
      'priorityHigh': 'High',
      'titleRequired': 'Title is required',
      'selectDueDate': 'Select Due Date',
      'noDueDate': 'No Due Date',
      'dueDate': 'Due Date',
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'confirmDeleteTitle': 'Confirm Delete',
      'confirmDeleteMessage': 'Are you sure you want to delete this task?',
      'loginTitle': 'Login',
      'registerTitle': 'Register',
      'emailHint': 'Email',
      'passwordHint': 'Password',
      'loginButton': 'Login',
      'registerButton': 'Register',
      'logout': 'Logout',
      'registerLink': 'Register',
      'loginLink': 'Login',
      'emailRequired': 'Email is required',
      'passwordRequired': 'Password is required',
      'invalidEmail': 'Invalid email format',
      'weakPassword': 'Password must be at least 6 characters',
      'emailInUse': 'Email is already in use',
      'wrongCredentials': 'Incorrect email or password',
      'loginSuccess': 'Login successful',
      'registerSuccess': 'Registration successful',
      'logoutSuccess': 'Logged out successfully',
      'logoutFailed': 'Failed to log out',
      'authError': 'Authentication error occurred',
      'retry': 'Retry',
      'taskDeleted': 'Task deleted',
      'undo': 'Undo',
      'refresh': 'Refresh',
      'deleteFailed': 'Failed to delete task',
      'updateFailed': 'Failed to update task',
      'userNotLoggedIn': 'User not logged in',
      'failedToLoadTasks': 'Failed to load tasks',
      'failedToAddTask': 'Failed to add task',
      'taskCompleted': 'Task completed',
      'taskNotCompleted': 'Task not completed',
      'taskUpdated': 'Task updated successfully',
      'taskAdded': 'Task added successfully',
      'networkError': 'No internet connection',
      'tooManyRequests': 'Too many requests, please try again later',
      'Low': 'Low Priority',
      'Medium': 'Medium Priority',
      'High': 'High Priority',
      'deleteTaskConfirmation': 'Are you sure you want to delete this task?',
      'confirmDelete': 'Confirm Delete',
      'delete': 'Delete',
      'taskAddedSuccess': 'Task added successfully',
      'taskDeletedSuccess': 'Task deleted successfully',
      'add': 'Add',
      'comfirmLogout': 'Are you sure you want to log out?',
      'logoutConfirmation': 'Logout Confirmation',
      'priority': 'Priority',
      'confirmExit': 'Confirm Exit',
      'unsavedChanges':
          'You have unsaved changes. Do you want to save before exiting?',
      'discard': 'Discard',
      'googleSignInCancelled': 'Google Sign-In was cancelled',
      'googleSignInFailed': 'Google Sign-In failed',
      'facebookSignInFailed': 'Facebook Sign-In failed',
      'appleSignInCancelled': 'Apple Sign-In was cancelled',
      'appleSignInFailed': 'Apple Sign-In failed',
      'networkErrorDuringLogout': 'Network error during logout',
      'welcomeBack': 'Welcome to the Smart List',
      'forgotPassword': 'Forgot Password?',
      'noAccount': 'Don\'t have an account?',
      'orContinueWith': 'or continue with',
      'termsAndPrivacy': 'Terms and Privacy Policy',
      'fullNameHint': 'Full Name',
      'confirmPasswordHint': 'Confirm Password',
      'fullNameRequired': 'Full name is required',
      'confirmPasswordRequired': 'Confirm password is required',
      'passwordStrength':
          'Password must be at least 8 characters with uppercase, lowercase, and number',
      'passwordsNotMatch': 'Passwords do not match',
      'alreadyHaveAccount': 'Already have an account?',
      'calendar': 'Calendar',
      'due': 'Due',
      'calendarPreferences': 'Calendar Preferences',
      'calendarView': 'Calendar View',
      'timeFormat': 'Time Format',
      'firstDayOfWeek': 'First Day of Week',
      'taskManagement': 'Task Management',
      'defaultTaskPriority': 'Default Task Priority',
      'taskManagementTitle': 'Task Management',
      'accountSettings': 'Account Settings',
      'changePassword': 'Change Password',
      'syncWithCloud': 'Sync with Cloud',
      'exportData': 'Export Data',
      'aboutHelp': 'About & Help',
      'helpCenter': 'Help Center',
      'privacyPolicy': 'Privacy Policy',
      'termsOfService': 'Terms of Service',
      'version': 'Version',
      'notifications': 'Notifications',
      'taskDueReminders': 'Task Due Reminders',
      'upcomingTasksAlerts': 'Upcoming Tasks Alerts',
      'notificationSound': 'Notification Sound',
      'vibration': 'Vibration',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'textSize': 'Text Size',
      'taskDueDateFormat': 'Task Due Date Format',
      'taskSortingPreferences': 'Task Sorting Preferences',
      'errorSavingTask': 'Error saving task',
      'offlineSynced': 'Offline changes synced',
      'noteAdded': 'Note added successfully',
      'noteUpdated': 'Note updated successfully',
      'noteDeleted': 'Note deleted successfully',
      'savedOffline': 'Saved offline, will sync when online',
      'failedToAddNote': 'Failed to add note',
      'failedToUpdateNote': 'Failed to update note',
      'failedToLoadNotes': 'Failed to load notes',
      'failedToGetToken': 'Failed to authenticate',
      "currentPassword": "Current Password",
      "newPassword": "New Password",
      "passwordChanged": "Password changed successfully",
      "changePasswordFailed": "Failed to change password",
      "requiresRecentLogin": "Please log in again to change your password",
      "resetPassword": "Reset Password",
      "resetPasswordSent": "Password reset email sent",
      "resetPasswordFailed": "Failed to send password reset email",
      "userNotFound": "User not found",
      'change': 'Change',
      'send': 'Send',
      'voiceInputTitle': 'Voice Input',
      'tapToRecord': 'Tap to Record',
      'recording': 'Recording...',
      'audioRecorded': 'Audio Recorded',
      'playAudio': 'Play Audio',
      'transcribedText': 'Transcribed Text',
      'saveAsAudio': 'Save as Audio',
      'saveAsText': 'Save as Text',
      'addVoiceInput': 'Add Voice Input',
      'audioAttached': 'Audio Attached',
      'failedToLoadAnalytics': 'Failed to load analytics data',
      "monthlyOverview" : "Monthly Overview",
      "productivityChart": "Productivity chart",
      "tasksFor": "Tasks for"
    },
    'vi': {
      'tasks': 'Công việc',
      'appTitle': 'Ứng dụng Danh sách Công việc',
      'taskListTitle': 'Công việc',
      'addTask': 'Thêm Công việc',
      'editTask': 'Sửa Công việc',
      'deleteTask': 'Xóa',
      'taskTitleHint': 'Tiêu đề Công việc',
      'taskDescriptionHint': 'Mô tả',
      'cancel': 'Hủy',
      'save': 'Lưu',
      'noTasks': 'Không có công việc nào. Thêm một công việc mới!',
      'analyticsTitle': 'Phân tích Năng suất',
      'teamTitle': 'Hợp tác Nhóm',
      'priorityLow': 'Thấp',
      'priorityMedium': 'Trung bình',
      'priorityHigh': 'Cao',
      'titleRequired': 'Tiêu đề là bắt buộc',
      'selectDueDate': 'Chọn Ngày Hết Hạn',
      'noDueDate': 'Không Có Ngày Hết Hạn',
      'dueDate': 'Ngày Hết Hạn',
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'confirmDeleteTitle': 'Xác nhận Xóa',
      'confirmDeleteMessage': 'Bạn có chắc chắn muốn xóa công việc này không?',
      'loginTitle': 'Đăng nhập',
      'registerTitle': 'Đăng ký',
      'emailHint': 'Email',
      'passwordHint': 'Mật khẩu',
      'loginButton': 'Đăng nhập',
      'registerButton': 'Đăng ký',
      'logout': 'Đăng xuất',
      'registerLink': 'Đăng ký',
      'loginLink': 'Đăng nhập',
      'emailRequired': 'Email là bắt buộc',
      'passwordRequired': 'Mật khẩu là bắt buộc',
      'invalidEmail': 'Định dạng email không hợp lệ',
      'weakPassword': 'Mật khẩu phải có ít nhất 6 ký tự',
      'emailInUse': 'Email đã được sử dụng',
      'wrongCredentials': 'Email hoặc mật khẩu không đúng',
      'loginSuccess': 'Đăng nhập thành công',
      'registerSuccess': 'Đăng ký thành công',
      'logoutSuccess': 'Đăng xuất thành công',
      'logoutFailed': 'Đăng xuất thất bại',
      'authError': 'Lỗi xác thực đã xảy ra',
      'retry': 'Thử lại',
      'taskDeleted': 'Công việc đã bị xóa',
      'undo': 'Hoàn tác',
      'refresh': 'Làm mới',
      'deleteFailed': 'Xóa công việc thất bại',
      'updateFailed': 'Cập nhật công việc thất bại',
      'userNotLoggedIn': 'Người dùng chưa đăng nhập',
      'failedToLoadTasks': 'Tải công việc thất bại',
      'failedToAddTask': 'Thêm công việc thất bại',
      'taskCompleted': 'Công việc đã hoàn thành',
      'taskNotCompleted': 'Công việc chưa hoàn thành',
      'taskUpdated': 'Công việc đã được cập nhật',
      'taskAdded': 'Công việc đã được thêm',
      'networkError': 'Không có kết nối internet',
      'tooManyRequests': 'Quá nhiều yêu cầu, vui lòng thử lại sau',
      'Low': 'Độ ưu tiên thấp',
      'Medium': 'Độ ưu tiên trung bình',
      'High': 'Độ ưu tiên cao',
      'deleteTaskConfirmation': 'Xác nhận xóa công việc',
      'confirmDelete': 'Xác nhận xóa',
      'delete': 'Xóa',
      'taskAddedSuccess': 'Công việc đã được thêm thành công',
      'taskDeletedSuccess': 'Công việc đã bị xóa thành công',
      'taskUpdatedSuccess': 'Công việc đã được cập nhật thành công',
      'add': 'Thêm',
      'confirmLogout': 'Bạn có chắc chắn muốn đăng xuất không?',
      'logoutConfirmation': 'Xác nhận đăng xuất',
      'priority': 'Độ ưu tiên',
      'confirmExit': 'Xác nhận thoát',
      'unsavedChanges':
          'Bạn có thay đổi chưa được lưu. Bạn có muốn lưu trước khi thoát không?',
      'discard': 'Bỏ qua',
      'googleSignInCancelled': 'Đăng nhập Google bị hủy',
      'googleSignInFailed': 'Đăng nhập Google thất bại',
      'facebookSignInFailed': 'Đăng nhập Facebook thất bại',
      'appleSignInCancelled': 'Đăng nhập Apple bị hủy',
      'appleSignInFailed': 'Đăng nhập Apple thất bại',
      'networkErrorDuringLogout': 'Lỗi mạng trong quá trình đăng xuất',
      'welcomeBack': 'Chào mừng bạn trở lại Smart List',
      'forgotPassword': 'Quên mật khẩu?',
      'noAccount': 'Chưa có tài khoản?',
      'orContinueWith': 'hoặc tiếp tục với',
      'termsAndPrivacy': 'Điều khoản và Chính sách quyền riêng tư',
      'fullNameHint': 'Họ và tên',
      'confirmPasswordHint': 'Xác nhận mật khẩu',
      'fullNameRequired': 'Họ và tên là bắt buộc',
      'confirmPasswordRequired': 'Xác nhận mật khẩu là bắt buộc',
      'passwordStrength':
          'Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường và số',
      'passwordsNotMatch': 'Mật khẩu không khớp',
      'alreadyHaveAccount': 'Đã có tài khoản?',
      'calendar': 'Lịch',
      'due': 'Hết hạn',
      'calendarPreferences': 'Tùy chọn Lịch',
      'calendarView': 'Chế độ xem Lịch',
      'timeFormat': 'Định dạng thời gian',
      'firstDayOfWeek': 'Ngày đầu tuần',
      'taskManagement': 'Quản lý Công việc',
      'defaultTaskPriority': 'Độ ưu tiên công việc mặc định',
      'taskManagementTitle': 'Quản lý Công việc',
      'accountSettings': 'Cài đặt Tài khoản',
      'changePassword': 'Đổi mật khẩu',
      'syncWithCloud': 'Đồng bộ với Đám mây',
      'exportData': 'Xuất Dữ liệu',
      'aboutHelp': 'Giới thiệu & Trợ giúp',
      'helpCenter': 'Trung tâm Trợ giúp',
      'privacyPolicy': 'Chính sách Quyền riêng tư',
      'termsOfService': 'Điều khoản Dịch vụ',
      'version': 'Phiên bản',
      'notifications': 'Thông báo',
      'taskDueReminders': 'Nhắc nhở công việc đến hạn',
      'upcomingTasksAlerts': 'Cảnh báo công việc sắp đến hạn',
      'notificationSound': 'Âm thanh thông báo',
      'vibration': 'Rung',
      'appearance': 'Giao diện',
      'theme': 'Chủ đề',
      'textSize': 'Kích thước văn bản',
      'taskDueDateFormat': 'Định dạng ngày hết hạn công việc',
      'taskSortingPreferences': 'Tùy chọn sắp xếp công việc',
      'errorSavingTask': 'Lỗi khi lưu công việc',
      'offlineSynced': 'Thay đổi ngoại tuyến đã được đồng bộ',
      'noteAdded': 'Ghi chú đã được thêm thành công',
      'noteUpdated': 'Ghi chú đã được cập nhật thành công',
      'noteDeleted': 'Ghi chú đã bị xóa thành công',
      'savedOffline': 'Đã lưu ngoại tuyến, sẽ đồng bộ khi trực tuyến',
      'failedToAddNote': 'Thêm ghi chú thất bại',
      'failedToUpdateNote': 'Cập nhật ghi chú thất bại',
      'failedToLoadNotes': 'Tải ghi chú thất bại',
      'failedToGetToken': 'Xác thực thất bại',
      "currentPassword": "Mật Khẩu Hiện Tại",
      "newPassword": "Mật Khẩu Mới",
      "passwordChanged": "Đổi mật khẩu thành công",
      "changePasswordFailed": "Không thể đổi mật khẩu",
      "requiresRecentLogin": "Vui lòng đăng nhập lại để đổi mật khẩu",
      "resetPassword": "Đặt Lại Mật Khẩu",
      "resetPasswordSent": "Email đặt lại mật khẩu đã được gửi",
      "resetPasswordFailed": "Không thể gửi email đặt lại mật khẩu",
      "userNotFound": "Không tìm thấy người dùng",
      'change': 'Thay đổi',
      'send': 'Gửi',
      'voiceInputTitle': 'Nhập liệu bằng giọng nói',
      'tapToRecord': 'Chạm để ghi âm',
      'recording': 'Đang ghi âm...',
      'audioRecorded': 'Âm thanh đã được ghi',
      'playAudio': 'Phát âm thanh',
      'transcribedText': 'Văn bản đã được chuyển đổi',
      'saveAsAudio': 'Lưu dưới dạng Âm thanh',
      'saveAsText': 'Lưu dưới dạng Văn bản',
      'addVoiceInput': 'Thêm Nhập liệu bằng giọng nói',
      'audioAttached': 'Âm thanh đã được đính kèm',
      'failedToLoadAnalytics': 'Failed to load analytics data',
      "monthlyOverview" : "Tổng quan hàng tháng",
      "productivityChart": "Biểu đồ năng suất",
      "tasksFor": "Nhiệm vụ cho"
    },
  };

  static String get(String key, Locale locale) {
    final languageCode = locale.languageCode;
    final translation =
        _translations[languageCode]?[key] ?? _translations['en']?[key];
    return translation ?? 'Missing translation for key: $key';
  }

  static const List<Locale> supportedLocales = [
    Locale('en', 'US'),
    Locale('vi', 'VN'),
  ];
}
