name: smartlist
description: "A Flutter To-do List application"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  speech_to_text: ^7.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.2
  connectivity_plus: ^6.1.4
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.2.8
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  flutter_launcher_icons: ^0.14.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/icon/app_icon.png

flutter_icons:
  android: true
  image_path: "lib/core/icon/app_icon.png"
